In [ ]:
import pandas as pd
with open('bill_data.txt','r+') as f:
    lines=f.read() # read as one string 
    a=[]
    b=[]
    c=['Jan','Feb','March','April','May','June','July','Aug','Sep','Oct','Nov','Dec','march','Imp']
    d=[]
    lines=lines.split('\n') #split by \n
    print(lines)
    for i in range(0,len(lines)):
        p=lines[i]
        a.append(p.replace(" ",""))
    
    print(a)
    for j in range(0,len(a)):
        for p in range(0,len(c)):
            if a[j].count(c[p])==0:
                pass
            else:
                b.append(a[j])
                
        
    
    print(d,end='\n')
    print(b)
    df=[]
     
    for z in range(0,len(b)):
        df.append(b[z].split(':'))
    print(df)

    dfd = pd.DataFrame(df,columns=['Month','Total','Food','Transport','Ex'])
    print(type(dfd['Total'][0]))
    
    
    #dfd.fillna(0)
            
    dfd.to_excel('result.xlsx',header=True)

['Expenses', 'March :  10, 728', 'April: 10,112.99', 'May: 9923', 'June: 10624', 'July: 10991 : 3947: 405:6639', 'Aug:   8086 :2663 :914 :4509', 'Sep: 9280:3033 :1160:5087', 'Oct: 8730:2917 :833 :4980 ', 'Nov: 8652:3020:733:4899', 'Dec:  9573 :3341:568:5664 ', 'Jan: 7146:1789 :  845 : 4512  ', 'Feb: 9558 :  3712 : 856 : 4990', 'March: Bal: 114459', '1march: account balance: 144740.37', '2 march: 106 transport + 90 food  + 20 food + 15 transport + 40 food', '3 march: 90 food + 28 food + 40 food', '4 march: 158 food + 15 transport ', '5 march: 100 food + 27 transport  + 28 food ', '6 march: 80 food +4500 ex + 68 food + 15 bus ', '7 march: 100 food + 60 ex + ', '8 march: 80 food + 30 food ', '9 march: 90 food + 35 food', '10 march: 92 food +', '11 March : 158 food ', '12 march: 20 food + 90 food + 33 food  + 15 bus', '13 march: 70 food + 23 bus+ 22 food  + 40 food', '14 march: 80 food + 30 food ', '15 march: 70 food + 30 bus + 40 food + ', '16 march: 70 food + 10 ex + 25 bus + 40 food', '17 march: 70 food + 15 bus + 40 food', '18 March: 70 food + 15 bus + 35 food ', '19 march: 70 food + 20 food ', '20 march: 20 food + 10 food + 245 food + 20 food + 10 food ', '21 march: 65 food ', '22 march: 123 food +', '23 march: 123 food + 30 food', '24 March : 30 food + 34 food + 600 transport', '28 March : 329 ex ', '31 March: 598 ex', 'March:122043.37 balance', 'Imp:11000 madhav PG has taken ', 'April:1544822.37 with salary balance']
['Expenses', 'March:10,728', 'April:10,112.99', 'May:9923', 'June:10624', 'July:10991:3947:405:6639', 'Aug:8086:2663:914:4509', 'Sep:9280:3033:1160:5087', 'Oct:8730:2917:833:4980', 'Nov:8652:3020:733:4899', 'Dec:9573:3341:568:5664', 'Jan:7146:1789:845:4512', 'Feb:9558:3712:856:4990', 'March:Bal:114459', '1march:accountbalance:144740.37', '2march:106transport+90food+20food+15transport+40food', '3march:90food+28food+40food', '4march:158food+15transport', '5march:100food+27transport+28food', '6march:80food+4500ex+68food+15bus', '7march:100food+60ex+', '8march:80food+30food', '9march:90food+35food', '10march:92food+', '11March:158food', '12march:20food+90food+33food+15bus', '13march:70food+23bus+22food+40food', '14march:80food+30food', '15march:70food+30bus+40food+', '16march:70food+10ex+25bus+40food', '17march:70food+15bus+40food', '18March:70food+15bus+35food', '19march:70food+20food', '20march:20food+10food+245food+20food+10food', '21march:65food', '22march:123food+', '23march:123food+30food', '24March:30food+34food+600transport', '28March:329ex', '31March:598ex', 'March:122043.37balance', 'Imp:11000madhavPGhastaken', 'April:1544822.37withsalarybalance']
[]
['March:10,728', 'April:10,112.99', 'May:9923', 'June:10624', 'July:10991:3947:405:6639', 'Aug:8086:2663:914:4509', 'Sep:9280:3033:1160:5087', 'Oct:8730:2917:833:4980', 'Nov:8652:3020:733:4899', 'Dec:9573:3341:568:5664', 'Jan:7146:1789:845:4512', 'Feb:9558:3712:856:4990', 'March:Bal:114459', '1march:accountbalance:144740.37', '2march:106transport+90food+20food+15transport+40food', '3march:90food+28food+40food', '4march:158food+15transport', '5march:100food+27transport+28food', '6march:80food+4500ex+68food+15bus', '7march:100food+60ex+', '8march:80food+30food', '9march:90food+35food', '10march:92food+', '11March:158food', '12march:20food+90food+33food+15bus', '13march:70food+23bus+22food+40food', '14march:80food+30food', '15march:70food+30bus+40food+', '16march:70food+10ex+25bus+40food', '17march:70food+15bus+40food', '18March:70food+15bus+35food', '19march:70food+20food', '20march:20food+10food+245food+20food+10food', '21march:65food', '22march:123food+', '23march:123food+30food', '24March:30food+34food+600transport', '28March:329ex', '31March:598ex', 'March:122043.37balance', 'Imp:11000madhavPGhastaken', 'April:1544822.37withsalarybalance']
[['March', '10,728'], ['April', '10,112.99'], ['May', '9923'], ['June', '10624'], ['July', '10991', '3947', '405', '6639'], ['Aug', '8086', '2663', '914', '4509'], ['Sep', '9280', '3033', '1160', '5087'], ['Oct', '8730', '2917', '833', '4980'], ['Nov', '8652', '3020', '733', '4899'], ['Dec', '9573', '3341', '568', '5664'], ['Jan', '7146', '1789', '845', '4512'], ['Feb', '9558', '3712', '856', '4990'], ['March', 'Bal', '114459'], ['1march', 'accountbalance', '144740.37'], ['2march', '106transport+90food+20food+15transport+40food'], ['3march', '90food+28food+40food'], ['4march', '158food+15transport'], ['5march', '100food+27transport+28food'], ['6march', '80food+4500ex+68food+15bus'], ['7march', '100food+60ex+'], ['8march', '80food+30food'], ['9march', '90food+35food'], ['10march', '92food+'], ['11March', '158food'], ['12march', '20food+90food+33food+15bus'], ['13march', '70food+23bus+22food+40food'], ['14march', '80food+30food'], ['15march', '70food+30bus+40food+'], ['16march', '70food+10ex+25bus+40food'], ['17march', '70food+15bus+40food'], ['18March', '70food+15bus+35food'], ['19march', '70food+20food'], ['20march', '20food+10food+245food+20food+10food'], ['21march', '65food'], ['22march', '123food+'], ['23march', '123food+30food'], ['24March', '30food+34food+600transport'], ['28March', '329ex'], ['31March', '598ex'], ['March', '122043.37balance'], ['Imp', '11000madhavPGhastaken'], ['April', '1544822.37withsalarybalance']]
<class 'str'>

In [16]:
gh=dfd['Total'][14:]
hj=[]
for i in gh:
    hj.append(i.split('+'))

print(hj[0])
hj1=[]
c=('t','s')
hj2=[]
hj3=[]
print(type(c))
for i in range(0,len(hj)):
    for j in range(0,len(hj[i])):
        if hj[i][j].endswith(c):
            hj1.append(hj[i][j])
        if hj[i][j].endswith('d'):
            hj2.append(hj[i][j])
        if hj[i][j].endswith('x'):
            hj3.append(hj[i][j])
            
            

print(hj1)
print(hj2)
print(hj3)
hj4=[]
hj6=[]
for i in range(0,len(hj1)):
    hj4.append(hj1[i].split('transport'))
    hj6.append(hj1[i].split('bus'))

print(hj4)
print(hj6)
hj5=[]

for i in range(0,len(hj4)):
    if len(hj4[i])==2:
        hj5.append(hj4[i][0])

print(hj5)
hj7=[]
for i in range(0,len(hj6)):
    if len(hj6[i])==2:
        hj7.append(hj6[i][0])

print(hj7)
hj8=hj5+hj7
print(hj8)
sum_t=0
for i in hj8:
    sum_t+=int(i)

print(sum_t)
hj9=[]
for i in range(0,len(hj2)):
    hj9.append(hj2[i].split('food'))
    

print(hj9)

hj10=[]

for i in range(0,len(hj9)):
    if len(hj9[i])==2:
        hj10.append(hj9[i][0])

print(hj10)



sum_f=0
for i in hj10:
    sum_f+=int(i)

print(sum_f)


hj11=[]
for i in range(0,len(hj3)):
    hj11.append(hj3[i].split('ex'))
    

print(hj11)
hj12=[]

for i in range(0,len(hj11)):
    if len(hj11[i])==2:
        hj12.append(hj11[i][0])

print(hj12)



sum_e=0
for i in hj12:
    sum_e+=int(i)

print(sum_e)

tot=sum_t+sum_f+sum_e

dfd1=pd.read_excel('result.xlsx',index_col=0)
dfd1.append({'Month':'March','Total':tot,'Food':sum_f,'Transport':sum_t,'Ex':sum_e},ignore_index='True')

print(dfd1)

['106transport', '90food', '20food', '15transport', '40food']
<class 'tuple'>
['106transport', '15transport', '15transport', '27transport', '15bus', '15bus', '23bus', '30bus', '25bus', '15bus', '15bus', '600transport']
['90food', '20food', '40food', '90food', '28food', '40food', '158food', '100food', '28food', '80food', '68food', '100food', '80food', '30food', '90food', '35food', '92food', '158food', '20food', '90food', '33food', '70food', '22food', '40food', '80food', '30food', '70food', '40food', '70food', '40food', '70food', '40food', '70food', '35food', '70food', '20food', '20food', '10food', '245food', '20food', '10food', '65food', '123food', '123food', '30food', '30food', '34food']
['4500ex', '60ex', '10ex', '329ex', '598ex']
[['106', ''], ['15', ''], ['15', ''], ['27', ''], ['15bus'], ['15bus'], ['23bus'], ['30bus'], ['25bus'], ['15bus'], ['15bus'], ['600', '']]
[['106transport'], ['15transport'], ['15transport'], ['27transport'], ['15', ''], ['15', ''], ['23', ''], ['30', ''], ['25', ''], ['15', ''], ['15', ''], ['600transport']]
['106', '15', '15', '27', '600']
['15', '15', '23', '30', '25', '15', '15']
['106', '15', '15', '27', '600', '15', '15', '23', '30', '25', '15', '15']
901
[['90', ''], ['20', ''], ['40', ''], ['90', ''], ['28', ''], ['40', ''], ['158', ''], ['100', ''], ['28', ''], ['80', ''], ['68', ''], ['100', ''], ['80', ''], ['30', ''], ['90', ''], ['35', ''], ['92', ''], ['158', ''], ['20', ''], ['90', ''], ['33', ''], ['70', ''], ['22', ''], ['40', ''], ['80', ''], ['30', ''], ['70', ''], ['40', ''], ['70', ''], ['40', ''], ['70', ''], ['40', ''], ['70', ''], ['35', ''], ['70', ''], ['20', ''], ['20', ''], ['10', ''], ['245', ''], ['20', ''], ['10', ''], ['65', ''], ['123', ''], ['123', ''], ['30', ''], ['30', ''], ['34', '']]
['90', '20', '40', '90', '28', '40', '158', '100', '28', '80', '68', '100', '80', '30', '90', '35', '92', '158', '20', '90', '33', '70', '22', '40', '80', '30', '70', '40', '70', '40', '70', '40', '70', '35', '70', '20', '20', '10', '245', '20', '10', '65', '123', '123', '30', '30', '34']
2947
[['4500', ''], ['60', ''], ['10', ''], ['329', ''], ['598', '']]
['4500', '60', '10', '329', '598']
5497
      Month                                          Total       Food  \
0     March                                         10,728        NaN
1     April                                      10,112.99        NaN
2       May                                           9923        NaN
3      June                                          10624        NaN
4      July                                          10991    3947.00
5       Aug                                           8086    2663.00
6       Sep                                           9280    3033.00
7       Oct                                           8730    2917.00
8       Nov                                           8652    3020.00
9       Dec                                           9573    3341.00
10      Jan                                           7146    1789.00
11      Feb                                           9558    3712.00
12    March                                            Bal  114459.00
13   1march                                 accountbalance  144740.37
14   2march  106transport+90food+20food+15transport+40food        NaN
15   3march                           90food+28food+40food        NaN
16   4march                            158food+15transport        NaN
17   5march                     100food+27transport+28food        NaN
18   6march                     80food+4500ex+68food+15bus        NaN
19   7march                                  100food+60ex+        NaN
20   8march                                  80food+30food        NaN
21   9march                                  90food+35food        NaN
22  10march                                        92food+        NaN
23  11March                                        158food        NaN
24  12march                     20food+90food+33food+15bus        NaN
25  13march                     70food+23bus+22food+40food        NaN
26  14march                                  80food+30food        NaN
27  15march                           70food+30bus+40food+        NaN
28  16march                       70food+10ex+25bus+40food        NaN
29  17march                            70food+15bus+40food        NaN
30  18March                            70food+15bus+35food        NaN
31  19march                                  70food+20food        NaN
32  20march            20food+10food+245food+20food+10food        NaN
33  21march                                         65food        NaN
34  22march                                       123food+        NaN
35  23march                                 123food+30food        NaN
36  24March                     30food+34food+600transport        NaN
37  28March                                          329ex        NaN
38  31March                                          598ex        NaN
39    March                               122043.37balance        NaN
40      Imp                          11000madhavPGhastaken        NaN
41    April                    1544822.37withsalarybalance        NaN

    Transport      Ex
0         NaN     NaN
1         NaN     NaN
2         NaN     NaN
3         NaN     NaN
4       405.0  6639.0
5       914.0  4509.0
6      1160.0  5087.0
7       833.0  4980.0
8       733.0  4899.0
9       568.0  5664.0
10      845.0  4512.0
11      856.0  4990.0
12        NaN     NaN
13        NaN     NaN
14        NaN     NaN
15        NaN     NaN
16        NaN     NaN
17        NaN     NaN
18        NaN     NaN
19        NaN     NaN
20        NaN     NaN
21        NaN     NaN
22        NaN     NaN
23        NaN     NaN
24        NaN     NaN
25        NaN     NaN
26        NaN     NaN
27        NaN     NaN
28        NaN     NaN
29        NaN     NaN
30        NaN     NaN
31        NaN     NaN
32        NaN     NaN
33        NaN     NaN
34        NaN     NaN
35        NaN     NaN
36        NaN     NaN
37        NaN     NaN
38        NaN     NaN
39        NaN     NaN
40        NaN     NaN
41        NaN     NaN

In [21]:
help(pd.io.excel)

Help on package pandas.io.excel in pandas.io:

NAME
    pandas.io.excel

PACKAGE CONTENTS
    _base
    _odfreader
    _openpyxl
    _util
    _xlrd
    _xlsxwriter
    _xlwt

CLASSES
    builtins.object
        pandas.io.excel._base.ExcelFile
        pandas.io.excel._base.ExcelWriter

    class ExcelFile(builtins.object)
     |  ExcelFile(io, engine=None)
     |
     |  Class for parsing tabular excel sheets into DataFrame objects.
     |  Uses xlrd. See read_excel for more documentation
     |
     |  Parameters
     |  ----------
     |  io : string, path object (pathlib.Path or py._path.local.LocalPath),
     |      file-like object or xlrd workbook
     |      If a string or path object, expected to be a path to xls or xlsx file.
     |  engine : string, default None
     |      If io is not a buffer or path, this must be set to identify io.
     |      Acceptable values are None or ``xlrd``.
     |
     |  Methods defined here:
     |
     |  __enter__(self)
     |
     |  __exit__(self, exc_type, exc_value, traceback)
     |
     |  __fspath__(self)
     |
     |  __init__(self, io, engine=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  close(self)
     |      close io if necessary
     |
     |  parse(self, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=True, mangle_dupe_cols=True, **kwds)
     |      Parse specified sheet(s) into a DataFrame
     |
     |      Equivalent to read_excel(ExcelFile, ...)  See the read_excel
     |      docstring for more info on accepted parameters
     |
     |      Returns
     |      -------
     |      DataFrame or dict of DataFrames
     |          DataFrame from the passed in Excel file.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  book
     |
     |  sheet_names

    class ExcelWriter(builtins.object)
     |  ExcelWriter(path, engine=None, **kwargs)
     |
     |  Class for writing DataFrame objects into excel sheets, default is to use
     |  xlwt for xls, openpyxl for xlsx.  See DataFrame.to_excel for typical usage.
     |
     |  Parameters
     |  ----------
     |  path : string
     |      Path to xls or xlsx file.
     |  engine : string (optional)
     |      Engine to use for writing. If None, defaults to
     |      ``io.excel.<extension>.writer``.  NOTE: can only be passed as a keyword
     |      argument.
     |  date_format : string, default None
     |      Format string for dates written into Excel files (e.g. 'YYYY-MM-DD')
     |  datetime_format : string, default None
     |      Format string for datetime objects written into Excel files
     |      (e.g. 'YYYY-MM-DD HH:MM:SS')
     |  mode : {'w', 'a'}, default 'w'
     |      File mode to use (write or append).
     |
     |      .. versionadded:: 0.24.0
     |
     |  Attributes
     |  ----------
     |  None
     |
     |  Methods
     |  -------
     |  None
     |
     |  Notes
     |  -----
     |  None of the methods and properties are considered public.
     |
     |  For compatibility with CSV writers, ExcelWriter serializes lists
     |  and dicts to strings before writing.
     |
     |  Examples
     |  --------
     |  Default usage:
     |
     |  >>> with ExcelWriter('path_to_file.xlsx') as writer:
     |  ...     df.to_excel(writer)
     |
     |  To write to separate sheets in a single file:
     |
     |  >>> with ExcelWriter('path_to_file.xlsx') as writer:
     |  ...     df1.to_excel(writer, sheet_name='Sheet1')
     |  ...     df2.to_excel(writer, sheet_name='Sheet2')
     |
     |  You can set the date format or datetime format:
     |
     |  >>> with ExcelWriter('path_to_file.xlsx',
     |                        date_format='YYYY-MM-DD',
     |                        datetime_format='YYYY-MM-DD HH:MM:SS') as writer:
     |  ...     df.to_excel(writer)
     |
     |  You can also append to an existing Excel file:
     |
     |  >>> with ExcelWriter('path_to_file.xlsx', mode='a') as writer:
     |  ...     df.to_excel(writer, sheet_name='Sheet3')
     |
     |  Methods defined here:
     |
     |  __enter__(self)
     |      # Allow use as a contextmanager
     |
     |  __exit__(self, exc_type, exc_value, traceback)
     |
     |  __fspath__(self)
     |
     |  __init__(self, path, engine=None, date_format=None, datetime_format=None, mode='w', **engine_kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  close(self)
     |      synonym for save, to make it more file-like
     |
     |  save(self)
     |      Save workbook to disk.
     |
     |  write_cells(self, cells, sheet_name=None, startrow=0, startcol=0, freeze_panes=None)
     |      Write given formatted cells into Excel an excel sheet
     |
     |      Parameters
     |      ----------
     |      cells : generator
     |          cell of formatted data to save to Excel sheet
     |      sheet_name : string, default None
     |          Name of Excel sheet, if None, then use self.cur_sheet
     |      startrow : upper left cell row to dump data frame
     |      startcol : upper left cell column to dump data frame
     |      freeze_panes: integer tuple of length 2
     |          contains the bottom-most row and right-most column to freeze
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  check_extension(ext) from abc.ABCMeta
     |      checks that path's extension against the Writer's supported
     |      extensions.  If it isn't supported, raises UnsupportedFiletypeError.
     |
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |
     |  __new__(cls, path, engine=None, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  engine
     |      Name of engine.
     |
     |  supported_extensions
     |      Extensions that writer engine supports.
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  __abstractmethods__ = frozenset({'engine', 'save', 'supported_extensio...
     |
     |  book = None
     |
     |  curr_sheet = None
     |
     |  path = None

FUNCTIONS
    read_excel(io, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skip_footer=0, skipfooter=0, convert_float=True, mangle_dupe_cols=True, **kwds)
        Read an Excel file into a pandas DataFrame.

        Support both `xls` and `xlsx` file extensions from a local filesystem or URL.
        Support an option to read a single sheet or a list of sheets.

        Parameters
        ----------
        io : str, ExcelFile, xlrd.Book, path object or file-like object
            Any valid string path is acceptable. The string could be a URL. Valid
            URL schemes include http, ftp, s3, and file. For file URLs, a host is
            expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

            If you want to pass in a path object, pandas accepts any ``os.PathLike``.

            By file-like object, we refer to objects with a ``read()`` method,
            such as a file handler (e.g. via builtin ``open`` function)
            or ``StringIO``.
        sheet_name : str, int, list, or None, default 0
            Strings are used for sheet names. Integers are used in zero-indexed
            sheet positions. Lists of strings/integers are used to request
            multiple sheets. Specify None to get all sheets.

            Available cases:

            * Defaults to ``0``: 1st sheet as a `DataFrame`
            * ``1``: 2nd sheet as a `DataFrame`
            * ``"Sheet1"``: Load sheet with name "Sheet1"
            * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
              as a dict of `DataFrame`
            * None: All sheets.

        header : int, list of int, default 0
            Row (0-indexed) to use for the column labels of the parsed
            DataFrame. If a list of integers is passed those row positions will
            be combined into a ``MultiIndex``. Use None if there is no header.
        names : array-like, default None
            List of column names to use. If file contains no header row,
            then you should explicitly pass header=None.
        index_col : int, list of int, default None
            Column (0-indexed) to use as the row labels of the DataFrame.
            Pass None if there is no such column.  If a list is passed,
            those columns will be combined into a ``MultiIndex``.  If a
            subset of data is selected with ``usecols``, index_col
            is based on the subset.
        usecols : int, str, list-like, or callable default None
            Return a subset of the columns.

            * If None, then parse all columns.
            * If int, then indicates last column to be parsed.

              .. deprecated:: 0.24.0
                 Pass in a list of int instead from 0 to `usecols` inclusive.

            * If str, then indicates comma separated list of Excel column letters
              and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
              both sides.
            * If list of int, then indicates list of column numbers to be parsed.
            * If list of string, then indicates list of column names to be parsed.

              .. versionadded:: 0.24.0

            * If callable, then evaluate each column name against it and parse the
              column if the callable returns ``True``.

              .. versionadded:: 0.24.0

        squeeze : bool, default False
            If the parsed data only contains one column then return a Series.
        dtype : Type name or dict of column -> type, default None
            Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
            Use `object` to preserve data as stored in Excel and not interpret dtype.
            If converters are specified, they will be applied INSTEAD
            of dtype conversion.

            .. versionadded:: 0.20.0

        engine : str, default None
            If io is not a buffer or path, this must be set to identify io.
            Acceptable values are None or xlrd.
        converters : dict, default None
            Dict of functions for converting values in certain columns. Keys can
            either be integers or column labels, values are functions that take one
            input argument, the Excel cell content, and return the transformed
            content.
        true_values : list, default None
            Values to consider as True.

            .. versionadded:: 0.19.0

        false_values : list, default None
            Values to consider as False.

            .. versionadded:: 0.19.0

        skiprows : list-like
            Rows to skip at the beginning (0-indexed).
        nrows : int, default None
            Number of rows to parse.

            .. versionadded:: 0.23.0

        na_values : scalar, str, list-like, or dict, default None
            Additional strings to recognize as NA/NaN. If dict passed, specific
            per-column NA values. By default the following values are interpreted
            as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
            '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
            'null'.
        keep_default_na : bool, default True
            If na_values are specified and keep_default_na is False the default NaN
            values are overridden, otherwise they're appended to.
        verbose : bool, default False
            Indicate number of NA values placed in non-numeric columns.
        parse_dates : bool, list-like, or dict, default False
            The behavior is as follows:

            * bool. If True -> try parsing the index.
            * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
              each as a separate date column.
            * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
              a single date column.
            * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
              result 'foo'

            If a column or index contains an unparseable date, the entire column or
            index will be returned unaltered as an object data type. For non-standard
            datetime parsing, use ``pd.to_datetime`` after ``pd.read_excel``.

            Note: A fast-path exists for iso8601-formatted dates.
        date_parser : function, optional
            Function to use for converting a sequence of string columns to an array of
            datetime instances. The default uses ``dateutil.parser.parser`` to do the
            conversion. Pandas will try to call `date_parser` in three different ways,
            advancing to the next if an exception occurs: 1) Pass one or more arrays
            (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
            string values from the columns defined by `parse_dates` into a single array
            and pass that; and 3) call `date_parser` once for each row using one or
            more strings (corresponding to the columns defined by `parse_dates`) as
            arguments.
        thousands : str, default None
            Thousands separator for parsing string columns to numeric.  Note that
            this parameter is only necessary for columns stored as TEXT in Excel,
            any numeric columns will automatically be parsed, regardless of display
            format.
        comment : str, default None
            Comments out remainder of line. Pass a character or characters to this
            argument to indicate comments in the input file. Any data between the
            comment string and the end of the current line is ignored.
        skip_footer : int, default 0
            Alias of `skipfooter`.

            .. deprecated:: 0.23.0
               Use `skipfooter` instead.
        skipfooter : int, default 0
            Rows at the end to skip (0-indexed).
        convert_float : bool, default True
            Convert integral floats to int (i.e., 1.0 --> 1). If False, all numeric
            data will be read in as floats: Excel stores all numbers as floats
            internally.
        mangle_dupe_cols : bool, default True
            Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
            'X'...'X'. Passing in False will cause data to be overwritten if there
            are duplicate names in the columns.
        **kwds : optional
                Optional keyword arguments can be passed to ``TextFileReader``.

        Returns
        -------
        DataFrame or dict of DataFrames
            DataFrame from the passed in Excel file. See notes in sheet_name
            argument for more information on when a dict of DataFrames is returned.

        See Also
        --------
        to_excel : Write DataFrame to an Excel file.
        to_csv : Write DataFrame to a comma-separated values (csv) file.
        read_csv : Read a comma-separated values (csv) file into DataFrame.
        read_fwf : Read a table of fixed-width formatted lines into DataFrame.

        Examples
        --------
        The file can be read using the file name as string or an open file object:

        >>> pd.read_excel('tmp.xlsx', index_col=0)  # doctest: +SKIP
               Name  Value
        0   string1      1
        1   string2      2
        2  #Comment      3

        >>> pd.read_excel(open('tmp.xlsx', 'rb'),
        ...               sheet_name='Sheet3')  # doctest: +SKIP
           Unnamed: 0      Name  Value
        0           0   string1      1
        1           1   string2      2
        2           2  #Comment      3

        Index and header can be specified via the `index_col` and `header` arguments

        >>> pd.read_excel('tmp.xlsx', index_col=None, header=None)  # doctest: +SKIP
             0         1      2
        0  NaN      Name  Value
        1  0.0   string1      1
        2  1.0   string2      2
        3  2.0  #Comment      3

        Column types are inferred but can be explicitly specified

        >>> pd.read_excel('tmp.xlsx', index_col=0,
        ...               dtype={'Name': str, 'Value': float})  # doctest: +SKIP
               Name  Value
        0   string1    1.0
        1   string2    2.0
        2  #Comment    3.0

        True, False, and NA values, and thousands separators have defaults,
        but can be explicitly specified, too. Supply the values you would like
        as strings or lists of strings!

        >>> pd.read_excel('tmp.xlsx', index_col=0,
        ...               na_values=['string1', 'string2'])  # doctest: +SKIP
               Name  Value
        0       NaN      1
        1       NaN      2
        2  #Comment      3

        Comment lines in the excel input file can be skipped using the `comment` kwarg

        >>> pd.read_excel('tmp.xlsx', index_col=0, comment='#')  # doctest: +SKIP
              Name  Value
        0  string1    1.0
        1  string2    2.0
        2     None    NaN

DATA
    __all__ = ['read_excel', 'ExcelWriter', 'ExcelFile']

FILE
    c:\users\jinesh\anaconda3\lib\site-packages\pandas\io\excel\__init__.py

In [3]:
import xlsxwriter
workbook = xlsxwriter.Workbook('result.xlsx')
print(workbook)
worksheet=workbook.worksheets()
print(worksheet)
chart1 = workbook.add_chart({'type': 'column'})
print(chart1)
chart1.add_series({ 
    'Month':       '= Sheet1!$B$2:$B$11', 
    'Total': '= Sheet1!$C$2:$C$11',
    }) 
chart1.set_title({'name':'Total Expenses'})
chart1.set_x_axis({'name':'Months'})
chart1.set_y_axis({'name':'Total'})
worksheet.insert_chart('H2', chart1)
workbook.close()

<xlsxwriter.workbook.Workbook object at 0x000001655C6A9708>
[]
<xlsxwriter.chart_column.ChartColumn object at 0x000001655C58EF48>

C:\Users\jinesh\Anaconda3\lib\site-packages\xlsxwriter\chart.py:124: UserWarning: Must specify 'values' in add_series()
  warn("Must specify 'values' in add_series()")

AttributeError: 'list' object has no attribute 'insert_chart'